services:
  nginx:
    image: nginx:alpine
    container_name: saltype-nginx
    volumes:
      # - ${SSL_VOLUME}
      - ./templates:/etc/nginx/templates
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - BACKEND=${BACKEND_PROXY}
      - FRONTEND=${FRONTEND_PROXY}
      - SERVER_NAME=${SERVER_NAME}
      - HTTP_PORT=${HTTP_PORT}
      # - HTTPS_PORT=${HTTPS_PORT}
      # - SSL_CERTIFICATE_PATH=${SSL_CERTIFICATE_PATH}
      # - SSL_CERTIFICATE_KEY_PATH=${SSL_CERTIFICATE_KEY_PATH}
    depends_on:
      - frontend
      - backend
    networks:
      - frontend-net
      - backend-net
    deploy:
      resources:
        limits:
          memory: 128M

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    read_only: true
    container_name: saltype-nuxt
    volumes:
      - ./frontend/server/data:/app/dist/data:ro
      - /tmp
    tmpfs:
      - /tmp
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - frontend-net
    deploy:
      resources:
        limits:
          memory: 256M

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    read_only: true
    container_name: saltype-django
    volumes:
      - ./backend:/app:ro
      - /tmp
    tmpfs:
      - /tmp
    environment:
      - DEBUG=${DEBUG:-false}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SQL_ENGINE=${DB_ENGINE}
      - SQL_DATABASE=${DB_NAME}
      - SQL_USER=${DB_USER}
      - SQL_PASSWORD=${DB_PASSWORD}
      - SQL_HOST=${DB_HOST}
      - SQL_PORT=${DB_PORT}
      - PYTHONIOENCODING=utf-8
    depends_on:
      - db
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          memory: 512M

  db:
    image: postgres:14-alpine
    read_only: true
    container_name: saltype-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /tmp
      - /var/run/postgresql
    tmpfs:
      - /tmp
      - /var/run/postgresql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

volumes:
  postgres_data:
